
const KEY="angels_agenda_v6"; const today=new Date().toISOString().slice(0,10);
const demo=[{id:"1",tutor:"Juliana Lima",whatsapp:"21987654321",pet:"Luna",raca:"Shih Tzu",servico:"Banho e Tosa",porte:"Pequeno",data:today,hora:"09:00",busca:true,obs:"Prefere produtos hipoalergênicos.",status:"Pendente",origem:"App"},{id:"2",tutor:"Carlos Eduardo",whatsapp:"21977778888",pet:"Thor",raca:"Golden Retriever",servico:"Banho",porte:"Grande",data:today,hora:"10:30",busca:false,obs:"",status:"Confirmado",origem:"App"},{id:"3",tutor:"Mariana Alves",whatsapp:"21966667777",pet:"Mia",raca:"Persa",servico:"Clubinho",porte:"Pequeno",data:today,hora:"13:00",busca:false,obs:"Meio período.",status:"Pendente",origem:"Cliente"}];
function load(){const s=localStorage.getItem(KEY); if(s) return JSON.parse(s); localStorage.setItem(KEY,JSON.stringify(demo)); return demo;}
function save(d){localStorage.setItem(KEY,JSON.stringify(d));}
function fmt(d){if(!d)return""; const p=d.split("-"); return `${p[2]}/${p[1]}/${p[0]}`;}
function wa(b){const phone=(b.whatsapp||"").replace(/\D/g,""); const msg=`Olá, ${b.tutor}! Somos da Angels Estética Animal. O agendamento do pet ${b.pet} para ${b.servico} está como ${b.status}. Data: ${fmt(b.data)} às ${b.hora}.`; return `https://wa.me/55${phone}?text=${encodeURIComponent(msg)}`;}
function card(b){return `<div class="booking"><div class="booking-top"><div><h4>${b.pet} — ${b.servico}</h4><p>Tutor: ${b.tutor} • ${b.raca||"Raça não informada"} • Origem: ${b.origem||"App"}</p><p>${fmt(b.data)} às ${b.hora} • ${b.busca?"Com busca e entrega":"Sem busca"}</p>${b.obs?`<p>Obs.: ${b.obs}</p>`:""}</div><span class="badge ${b.status}">${b.status}</span></div><div class="booking-actions"><button class="ok" onclick="setStatus('${b.id}','Confirmado')">Confirmar</button><button onclick="setStatus('${b.id}','Atendimento')">Atendimento</button><button onclick="setStatus('${b.id}','Concluído')">Finalizar</button><button class="no" onclick="setStatus('${b.id}','Cancelado')">Cancelar</button><button class="wa" onclick="window.open('${wa(b)}','_blank')">WhatsApp</button></div></div>`}
function render(){const items=load().sort((a,b)=>(a.data+a.hora).localeCompare(b.data+b.hora)); document.getElementById("countHoje").textContent=items.filter(x=>x.data===today).length; document.getElementById("countPendentes").textContent=items.filter(x=>x.status==="Pendente").length; document.getElementById("countConfirmados").textContent=items.filter(x=>x.status==="Confirmado").length; document.getElementById("countClubinho").textContent=items.filter(x=>x.servico==="Clubinho").length; const empty=`<div class="empty">Nenhum agendamento cadastrado ainda.</div>`; document.getElementById("recentList").innerHTML=items.slice(0,3).map(card).join("")||empty; document.getElementById("agendaList").innerHTML=items.map(card).join("")||empty;}
function setStatus(id,status){const d=load(); const i=d.find(x=>x.id===id); if(i){i.status=status; save(d); render();}}
function showScreen(id){document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active")); document.getElementById(id).classList.add("active"); document.querySelectorAll(".bottom-nav button").forEach(b=>b.classList.toggle("active",b.dataset.screen===id)); scrollTo({top:0,behavior:"smooth"});}
document.querySelectorAll(".bottom-nav button").forEach(btn=>btn.addEventListener("click",()=>showScreen(btn.dataset.screen)));
document.getElementById("bookingForm").addEventListener("submit",e=>{e.preventDefault(); const f=Object.fromEntries(new FormData(e.target).entries()); const d=load(); d.push({id:String(Date.now()),...f,busca:Boolean(f.busca),status:"Pendente",origem:"App"}); save(d); e.target.reset(); render(); showScreen("agenda");});
async function copyClientMessage(){const text=document.getElementById("clientMessage").innerText.trim(); try{await navigator.clipboard.writeText(text); alert("Mensagem copiada!");}catch(e){alert(text);}}
render();
